spring:
  application:
    name: log-service
  datasource:
    url: jdbc:mysql://${ip}:3307/${db_name}?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: lxh123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      server-addr: ${nacos-ip}:8848
      username: nacos
      password: ${password}
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: basic
      circuitbreaker:
        enabled: true

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cityseason.log.domain.po
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      id-type: assign_id


ip: 118.89.73.14
nacos-ip: 117.33.163.179
password: lxh123456
db_name: logs


server:
  port: 9080

